### ISSUE TITLE
Validations for checkout

### ISSUE THREAD

**Issue by omcrobbie** [distres117/stackstore-teamwin#89]
form requires email and address

**Comment by omcrobbie** [comment]
there should be some indicator that the fields need to be populated.  The email must be a valid email and the submit button should be disabled until the fields are filled appropriately.

**Comment by flexjames** [comment]
I've already disabled the account creation button unless there is a valid email address on the account creation page.   Is this for when guest want to checkout?

**Comment by omcrobbie** [comment]
both guest and auth user
