### ISSUE TITLE
Admin dashboard mechanics

### ISSUE THREAD

**Issue by omcrobbie** [distres117/stackstore-teamwin#97]
order, product, user management.  Backend should ensure that session user is admin before performing any of this.  See workshop for details

**Comment by omcrobbie** [comment]
I think it might be a good idea to create a router for handling all admin tasks, that way we could mount some middle ware to ensure that the session's user is an admin.  Thoughts?

**Comment by flexjames** [comment]
I'm closing this, as we discussed we didn't need to create another router file.
