### ISSUE TITLE
uploading pictures

### ISSUE THREAD

**Issue by omcrobbie** [distres117/stackstore-teamwin#98]
new products and categories can have pictures associated with them.  We need a mechanism for sending pictures to our api.

**Comment by jaylupus** [comment]
Is this supposed to be part of the admin's interface?

**Comment by omcrobbie** [comment]
yes, I'm working the ui view now.   That's why it's in the backlog.

**Comment by omcrobbie** [comment]
This functionality will be used in the admin-products view.  All we need is a backend route that will accept this type of data, and save it to a folder on the server.
